from importlib.metadata import PackageNotFoundError, version

from .bootstrap import init_workspace, main as bootstrap_main, parse_args as bootstrap_parse_args
from .cli import main, parse_args
from .config import _ensure_list_command, get_history_dir, load_config
from .models import (
    DEFAULT_CONFIG_FILE,
    DEFAULT_EVALUATION_BRIEF,
    DEFAULT_HISTORY_DIR,
    DEFAULT_HISTORY_LIMIT,
    DEFAULT_TASK_BRIEF,
    DEFAULT_WORKSPACE_DIRNAME,
    REQUIRED_STAGES,
    STATE_SCHEMA_VERSION,
    STATUS_COMPLETED,
    STATUS_FAILED,
    STATUS_PENDING,
    STATUS_RUNNING,
    STATUS_TOKENS,
    AgentConfig,
    SafeDict,
    StageConfig,
    WorkflowConfig,
    WorkflowError,
)
from .resources import default_brief_path, default_stage_template_path, resolve_workspace_dir
from .runtime import (
    append_history_entry,
    build_issue_delta,
    build_cycle_notes,
    build_history_entry,
    finalize_run,
    init_progress,
    load_history_entries,
    render_history_context,
    render_run_summary_markdown,
    render_status_markdown,
    run_stage,
    run_workflow,
    write_history_files,
    write_run_summary,
    write_status_files,
)
from .text import (
    build_cycle_context,
    dedupe_preserve_order,
    extract_reported_session_id,
    extract_token_totals,
    extract_first_json,
    parse_assessment,
    read_text_file,
    render_issue_bar,
    render_prompt,
    shorten_text,
    summarize_items,
)

try:
    __version__ = version("maker-checker")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.1.0"

__all__ = [
    "DEFAULT_EVALUATION_BRIEF",
    "DEFAULT_CONFIG_FILE",
    "DEFAULT_HISTORY_DIR",
    "DEFAULT_HISTORY_LIMIT",
    "DEFAULT_TASK_BRIEF",
    "DEFAULT_WORKSPACE_DIRNAME",
    "REQUIRED_STAGES",
    "STATE_SCHEMA_VERSION",
    "STATUS_COMPLETED",
    "STATUS_FAILED",
    "STATUS_PENDING",
    "STATUS_RUNNING",
    "STATUS_TOKENS",
    "AgentConfig",
    "SafeDict",
    "StageConfig",
    "WorkflowConfig",
    "WorkflowError",
    "__version__",
    "_ensure_list_command",
    "append_history_entry",
    "bootstrap_main",
    "bootstrap_parse_args",
    "build_cycle_context",
    "build_issue_delta",
    "build_cycle_notes",
    "build_history_entry",
    "default_brief_path",
    "default_stage_template_path",
    "dedupe_preserve_order",
    "extract_reported_session_id",
    "extract_token_totals",
    "extract_first_json",
    "finalize_run",
    "get_history_dir",
    "init_workspace",
    "init_progress",
    "load_config",
    "load_history_entries",
    "main",
    "parse_args",
    "parse_assessment",
    "read_text_file",
    "render_history_context",
    "render_issue_bar",
    "render_prompt",
    "render_run_summary_markdown",
    "render_status_markdown",
    "resolve_workspace_dir",
    "run_stage",
    "run_workflow",
    "shorten_text",
    "summarize_items",
    "write_history_files",
    "write_run_summary",
    "write_status_files",
]
